language: python
python: '2.7'
before_install:
- npm install -g jshint
- npm install -g bower
install:
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- bin/test --all
- bin/code-analysis
after_success:
- bin/test-coverage
after_script:
- travis-artifacts upload --path parts/test
- travis-artifacts upload --target-path latest --path parts/test
env:
  global:
  - ARTIFACTS_S3_BUCKET=plone.app.angularjs
  - secure: UCiLZczGYwCt0fr1DXYQ9X6aU1R/Y/dM2ocnyLNZ63fdE3UCzg6pUJCw+sVVlECsa1KSB4k6breSqr4km0pUy+SnOH7kd5XFGbGzGq5UW8XC+Z0sRUfVllj+7V1B9jlfs7b85BTnQB3FarEVB8TgGnCRL1Iiw5QT+C4HIKSI0bk=
  - secure: e0JB0JL7Z/KdaUAwpsX+8Swv5s7yVdhXI97zca6ryR50hqKYyBOQ+6Ay8UdWwVIZKgk65rB20AnuC2+0Mk4CPWtVFOjvkWJDQj6S3ULvAo8adF2+VJLm7T/PME0Co/l6373eUcIFf3DlOOd9zBM7cVnxDS3FtZdWT6iBsZlwbfs=
