language: python
python: '2.7'
before_install:
- npm install -g jshint
- npm install -g bower
install:
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- bin/test --all
- bin/code-analysis
after_success:
- bin/test-coverage
after_script:
- travis-artifacts upload --path parts/test
- travis-artifacts upload --target-path latest --path parts/test
env:
  global:
  - ARTIFACTS_S3_BUCKET=plone.app.angularjs
  - secure: VZGqP+9gojK9JPyNp0CEEfvJqe+k7cqoQtzr1fBQq0LGh6EP2qneBbT5ZuFzcjh3XOLlNPnyDST8ixl4J4qhJH9z4C3bPxL9t+xdDDFuRqkp3w174PQzhl8dJ6NT/gN3v+y+LoDrV49MCKrQ33arsJ14rQ9zTA9t3H9JEPJq+5A=
  - secure: ZFEgbFb0ILTEYB+xx//mO8SCkHmrrB5aMIeV3JvFa+SxJymdpNysIKBxVq2AY6na2vH9ozVky3lkKgiixSmyasivOBAVo/pap1l3SXJBClLqVPqvhJzA4ILX5Wpe2s36uQVPB+thDh9X03Gzopj1a/TU2ycjf1icUbExVwyp+do=
